### ISSUE TITLE
Memory leak issue

### ISSUE THREAD

**Issue by LuisLegreaux39** [NightCafeStudio/react-render-if-visible#13]
Hi,

I am currently using the library to handle map of choices in my app using a Material UI Accordion for the user to handle when the component(the one using the render-if-visible) appears on his screen but when this is hidden and  this error shows up on my console .
<img width="1031" alt="Screen Shot 2022-07-20 at 10 23 29 PM" src="https://user-images.githubusercontent.com/59577641/180116252-21aa142d-2508-4712-b000-132fca40812b.png">

I have found many reasons why of the memory leak and tried most of it, but this one seems to be related to the component itself, can you please help me?

**Comment by iamjoshua** [comment]
Same. The observer is not calling unobserve when useEffect cleans up...apparently ever from what I can tell. A memory leak is right!

**Comment by iamjoshua** [comment]
Seems to be related to the ref being lost before cleanup. This explains it: https://stackoverflow.com/questions/67069827/cleanup-ref-issues-in-react/67069936#67069936

I modified the component to use a local variable inside of useEffect. I'd submit a pull request but seeing as there are already two unmerged requests from a looooong time ago I suspect it won't get merged.

**Comment by GusRuss89** [comment]
@iamjoshua please submit the PR and I'll look into this issue :)

The other two old PRs should be closed I think, they're superseded by the React 17 update.
