### ISSUE TITLE
Only use Axios to fetch Item data when it is near/visible on viewport?

### ISSUE THREAD

**Issue by yelnyaface** [NightCafeStudio/react-render-if-visible#9]
I want to fetch only the item data in the list when the item is near/visible on viewport, is that a good thing in terms of page loading speed/API request calls? how do I modify the code to do that?

**Comment by GusRuss89** [comment]
Yes, this can be a good idea. You don't need to modify any code to do that, if your component does it's own data fetching (e.g. in a `useEffect(() => { fetchData() }, [])` then all you need to do is wrap the component in `<RenderIfVisible />` and it will do exactly what you're wanting.

**Comment by yelnyaface** [comment]
but dont I need to customize `render-if-visible.tsx` and check if `entries[0].isIntersecting` to execute a custom `fetch` async function when the item is in range of `1000px`? or is there another way?

**Comment by GusRuss89** [comment]
You don't need to do that, because your component will only be mounted when it comes within 1000px, so your data fetching in `useEffect` will only run when the component is within 1000px of the viewport.

If your data fetching is done in some other layer (i.e. not in your component) then you should probably make a new IntersectionObserver to trigger it - that's not what this utility is made for.

**Comment by yelnyaface** [comment]
I see, something like this right?

```
            {
                data.categories.length > 0 && data.categories.map((category, index) => {

                    return (

                        <RenderIfVisible defaultHeight={ESTIMATED_ITEM_HEIGHT}>

                            <FoodListItem key={index} category={category} selectFoodHandler={selectFoodHandler}/> // --> call async axios inside here?

                        </RenderIfVisible>

                    )

                })
            }
```

**Comment by GusRuss89** [comment]
If by "inside here" you mean inside the `<FoodListItem />` component then yes, that's right.
